# Generated by Django 6.1.1 on 2026-09-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
